---
title: "import_viz"
author: "Ella Zhang"
date: "11/3/2020"
output: html_document
---

## Preparation

```{r setup, include = TRUE, message = FALSE, warning = FALSE}

# Load packages used
library(knitr)
library(car)
library(AER)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(gridExtra)
library(lubridate)
library(RColorBrewer)

# Set up
opts_chunk$set(echo = TRUE)
options(digits = 3)
opts_knit$set(root.dir ="~/Desktop/NatlFisheriesGit/2_data")

# Remove objects from the previous session
rm(list = ls(all = TRUE))

# Load the data set
dta <- read.csv("output/build/monthly_cleaned.csv")
dta = subset(dta, select = -c(X))
dta$year_month <- as.yearmon(paste(dta$year, dta$month), "%Y %B")
dta = as_tibble(dta)
glimpse(dta)

```

## Data Visualization

```{r tidy = FALSE, message = FALSE}

dta %>% 
  group_by(country_name) %>% 
  summarise(volume_sum = sum(volume_kg)) %>% 
  arrange(desc(volume_sum))

```

```{r tidy = FALSE, message = FALSE}

dta_country = dta %>% 
  group_by(year_month, country_name) %>% 
  summarise(volume_sum = sum(volume_kg)/1000) %>% 
  filter(country_name %in% c("VIETNAM","CHINA"))

dta_country

```

```{r fig.width = 7, fig.height = 3, message = FALSE}

ggplot(dta_country,aes(year_month,volume_sum)) + 
  geom_path(aes(color=country_name)) + 
  geom_vline(xintercept = as.yearmon(c('Mar 2016','Nov 2019')), 
             color='steelblue4', linetype='dashed') + 
  annotate('text', x = as.yearmon('Mar 2016'), y = 14500, 
           label = ' Mar 2016:\n Inspection responsibility\n transferred from FDA to USDA', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  annotate('text', x = as.yearmon('Nov 2019'), y = 14500, 
           label = ' Nov 2019:\n USDA granted\n equivalence to\n Vietnam and\n China', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  labs(title = 'Volume of Catfish Imported from China and Vietnam by Month from 2012 to 2020', 
       x = 'Date', y = 'Volume of Catfish Imported (thousand kg)', color = 'Country Name') + 
  scale_x_yearmon(breaks = seq(from = min(dta_country$year_month), 
                               to = as.yearmon('Mar 2020'),
                               by = 0.25)) + 
  theme_bw() + 
  theme(plot.title = element_text(face = 'bold'), 
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_blank())

ggsave('output/figures/import/catfish_import_countries.png',dpi=300)

```

```{r tidy = FALSE, message = FALSE}

dta_vietnam = dta %>% 
  group_by(year_month, country_name) %>% 
  summarise(volume_sum = sum(volume_kg)/1000,
            value_sum = sum(value_USD)/1000) %>% 
  filter(country_name %in% c("VIETNAM"))

dta_vietnam
summary(dta_vietnam)

```

```{r fig.width = 7, fig.height = 3, message = FALSE}

ggplot(dta_vietnam,aes(year_month, volume_sum)) + 
  geom_path() + 
  geom_vline(xintercept = as.yearmon(c('Mar 2016','Nov 2019')), 
             color='steelblue4', linetype='dashed') + 
  annotate('text', x = as.yearmon('Mar 2016'), y = 14500, 
           label = ' Mar 2016:\n Inspection responsibility\n transferred from FDA to USDA', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  annotate('text', x = as.yearmon('Nov 2019'), y = 14500, 
           label = ' Nov 2019:\n USDA granted\n equivalence to\n Vietnam', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  labs(title = 'Volume of Catfish Imported from Vietnam by Month from 2012 to 2020', 
       x = 'Date', y = 'Volume of Catfish Imported from Vietnam (thousand kg)') + 
  scale_x_yearmon(breaks = seq(from = min(dta_vietnam$year_month), 
                               to = as.yearmon('Mar 2020'),
                               by = 0.25)) + 
  theme_bw() + 
  theme(plot.title = element_text(face = 'bold'), 
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_blank())

ggsave('output/figures/import/catfish_vietnam_monthly.png',dpi=300)

```

```{r fig.width = 7, fig.height = 3, message = FALSE}

ggplot(dta_vietnam,aes(year_month, value_sum)) + 
  geom_path() + 
  geom_vline(xintercept = as.yearmon(c('Mar 2016','Nov 2019')), 
             color='steelblue4', linetype='dashed') + 
  annotate('text', x = as.yearmon('Mar 2016'), y = 54500, 
           label = ' Mar 2016:\n Inspection responsibility\n transferred from FDA to USDA', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  annotate('text', x = as.yearmon('Nov 2019'), y = 54500, 
           label = ' Nov 2019:\n USDA granted\n equivalence to\n Vietnam', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  labs(title = 'Value of Catfish Imported from Vietnam by Month from 2012 to 2020', 
       x = 'Date', y = 'Value of Catfish Imported from Vietnam (thousand USD)') + 
  scale_x_yearmon(breaks = seq(from = min(dta_vietnam$year_month), 
                               to = as.yearmon('Mar 2020'),
                               by = 0.25)) + 
  theme_bw() + 
  theme(plot.title = element_text(face = 'bold'), 
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_blank())

ggsave('output/figures/import/catfish_vietnam_value_monthly.png',dpi=300)

```

```{r tidy = FALSE, message = FALSE}

dta_vietnam_season = dta_vietnam %>% 
  mutate(dategroup = round_date(as.Date(year_month), "3 months")) %>%
  group_by(dategroup) %>%
  summarise(season_volume = sum(volume_sum)/1000,
            season_value = sum(value_sum)/1000)

dta_vietnam_season$dategroup = ymd(dta_vietnam_season$dategroup %m+% months(2))

dta_vietnam_season

# dta_vietnam['volume_sum'] %>% slice(1:3) %>% sum()

```

```{r fig.width = 7, fig.height = 3, message = FALSE}

ggplot(dta_vietnam_season,aes(dategroup, season_volume)) + 
  geom_point(size=2) + 
  geom_path() + 
  geom_vline(xintercept = as.Date(c('2016-03-01','2019-11-05')),
             color='steelblue4', linetype='dashed') +
  annotate('text', x = as.Date('2016-03-01'), y = 39,
           label = ' Mar 2016:\n Inspection responsibility\n transferred from FDA to USDA',
           size = 3, color = 'steelblue4', hjust = 0) +
  annotate('text', x = as.Date('2019-11-05'), y = 39,
           label = ' Nov 2019:\n USDA granted\n equivalence to\n Vietnam',
           size = 3, color = 'steelblue4', hjust = 0) +
  labs(title = 'Volume of Catfish Imported from Vietnam by 3 Months from 2012 to 2020', 
       x = 'Date', y = 'Volume of Catfish Imported from Vietnam (million kg)') + 
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_bw() + 
  theme(plot.title = element_text(face = 'bold'),
        panel.grid.minor.x = element_blank())

ggsave('output/figures/import/catfish_vietnam_3months.png',dpi=300)

```

```{r tidy = FALSE, message = FALSE}

dta_vietnam_halfyear = dta_vietnam

dta_vietnam_halfyear$year_month_adjusted = ymd(as.Date(dta_vietnam_halfyear$year_month) %m-% months(2))

dta_vietnam_halfyear = dta_vietnam_halfyear %>% 
  mutate(dategroup = ceiling_date(year_month_adjusted, "6 months")) %>%
  group_by(dategroup) %>%
  summarise(halfyear_volume = sum(volume_sum)/1000,
            halfyear_value = sum(value_sum)/1000)

dta_vietnam_halfyear$dategroup = ymd(dta_vietnam_halfyear$dategroup %m+% months(2))

dta_vietnam_halfyear

# dta_vietnam['volume_sum'] %>% slice(1:6) %>% sum()

```

```{r fig.width = 7, fig.height = 3, message = FALSE}

ggplot(dta_vietnam_halfyear,aes(dategroup, halfyear_volume)) + 
  geom_point(size=2) + 
  geom_path() + 
  geom_vline(xintercept = as.Date(c('2016-03-01','2019-11-05')),
             color='steelblue4', linetype='dashed') +
  annotate('text', x = as.Date('2016-03-01'), y = 52,
           label = ' Mar 2016:\n Inspection responsibility\n transferred from FDA to USDA',
           size = 3, color = 'steelblue4', hjust = 0) +
  annotate('text', x = as.Date('2019-11-05'), y = 52,
           label = ' Nov 2019:\n USDA granted\n equivalence to\n Vietnam',
           size = 3, color = 'steelblue4', hjust = 0) +
  labs(title = 'Volume of Catfish Imported from Vietnam by 6 Months from 2012 to 2020', 
       x = 'Date', y = 'Volume of Catfish Imported from Vietnam (million kg)') + 
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_bw() + 
  theme(plot.title = element_text(face = 'bold'),
        panel.grid.minor.x = element_blank())

ggsave('output/figures/import/catfish_vietnam_6months.png',dpi=300)

```

```{r tidy = FALSE, message = FALSE}

dta_vietnam_year = dta_vietnam

dta_vietnam_year$year_month_adjusted = ymd(as.Date(dta_vietnam_year$year_month) %m-% months(2))

dta_vietnam_year = dta_vietnam_year %>% 
  mutate(dategroup = ceiling_date(year_month_adjusted, "1 year")) %>%
  group_by(dategroup) %>%
  summarise(year_volume = sum(volume_sum)/1000,
            year_value = sum(value_sum)/1000)

dta_vietnam_year$dategroup = ymd(dta_vietnam_year$dategroup %m+% months(2))

dta_vietnam_year

# dta_vietnam['volume_sum'] %>% slice(1:12) %>% sum()

```

```{r fig.width = 7, fig.height = 3, message = FALSE}

ggplot(dta_vietnam_year,aes(dategroup, year_volume)) + 
  geom_point(size=3) + 
  geom_path() + 
  geom_vline(xintercept = as.Date(c('2016-03-01','2019-11-05')),
             color='steelblue4', linetype='dashed') +
  annotate('text', x = as.Date('2016-03-01'), y = 102,
           label = ' Mar 2016:\n Inspection responsibility\n transferred from FDA to USDA',
           size = 3, color = 'steelblue4', hjust = 0) +
  annotate('text', x = as.Date('2019-11-05'), y = 102,
           label = ' Nov 2019:\n USDA granted\n equivalence to\n Vietnam',
           size = 3, color = 'steelblue4', hjust = 0) +
  labs(title = 'Volume of Catfish Imported from Vietnam by Year from 2012 to 2020', 
       x = 'Date', y = 'Volume of Catfish Imported from Vietnam (million kg)') + 
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_bw() + 
  theme(plot.title = element_text(face = 'bold'),
        panel.grid.minor.x = element_blank())

ggsave('output/figures/import/catfish_vietnam_1year.png',dpi=300)

```

```{r tidy = FALSE, message = FALSE}

dta_china = dta %>% 
  group_by(year_month, country_name) %>% 
  summarise(volume_sum = sum(volume_kg)/1000,
            value_sum = sum(value_USD)/1000) %>% 
  filter(country_name %in% c("CHINA"))

dta_china

```

```{r fig.width = 7, fig.height = 3, message = FALSE}

ggplot(dta_china,aes(year_month, volume_sum)) + 
  geom_path() + 
  geom_vline(xintercept = as.yearmon(c('Mar 2016','Nov 2019')), 
             color='steelblue4', linetype='dashed') + 
  annotate('text', x = as.yearmon('Mar 2016'), y = 1150, 
           label = ' Mar 2016:\n Inspection responsibility\n transferred from FDA to USDA', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  annotate('text', x = as.yearmon('Nov 2019'), y = 1150, 
           label = ' Nov 2019:\n USDA granted\n equivalence to\n China', 
           size = 3, color = 'steelblue4', hjust = 0) + 
  labs(title = 'Volume of Catfish Imported from China by Month from 2012 to 2020', 
       x = 'Date', y = 'Volume of Catfish Imported from China (thousand kg)') + 
  scale_x_yearmon(breaks = seq(from = min(dta_china$year_month), 
                               to = as.yearmon('Mar 2020'),
                               by = 0.25)) + 
  theme_bw() + 
  theme(plot.title = element_text(face = 'bold'), 
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_blank())

ggsave('output/figures/import/catfish_china_monthly.png',dpi=300)

```

```{r tidy = FALSE, message = FALSE}

dta_map = dta %>% 
  group_by(country_name) %>% 
  summarise(volume_sum = sum(volume_kg)/1000000) %>% 
  arrange(desc(volume_sum)) %>% 
  filter(volume_sum > 0.1)
  

dta_map$country_name <- tolower(dta_map$country_name)
substr(dta_map$country_name, 1, 1) <- toupper(substr(dta_map$country_name, 1, 1))

dta_map

```

```{r tidy = FALSE, message = FALSE}

library(maps)
world_map <- map_data("world")
map_subset = world_map %>%
  full_join(dta_map, by = c("region" = "country_name")) %>%
  filter(region != "Antarctica")

plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)

ggplot(data = map_subset, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = volume_sum), color = "gray", size = 0.1) +
  scale_fill_distiller(palette ="Blues", direction = 1, na.value="white") +
  guides(fill = guide_colourbar(title.position="top", title.hjust = 0.5, 
                                barwidth = 15, barheight = 1, ticks = FALSE)) +
  ggtitle("Major Catfish Exporting Countries to the United States from 2012 to 2020") +
  labs(fill = "Volume of Catfish Imported (million kg)") +
  plain +
  theme(legend.position="bottom", 
        legend.title = element_text(size=10),
        legend.background = element_rect(fill="white", size=0.1, 
                                         linetype="solid", 
                                         color ="black"))

ggsave('output/figures/import/catfish_import_map.png',dpi=300)

```
