---
title: "Regression"
author: "Ella Zhang"
date: "11/25/2020"
output: html_document
---

## Preparation

```{r setup, include = TRUE, message = FALSE, warning = FALSE}

# Load packages used
library(knitr)
library(car)
library(AER)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(gridExtra)
library(lubridate)
library(RColorBrewer)
library(jtools)
library(stargazer)
library(huxtable)

# Set up
opts_chunk$set(echo = TRUE)
options(digits = 3)
opts_knit$set(root.dir ="~/Desktop/NatlFisheriesGit/2_data")

# Remove objects from the previous session
rm(list = ls(all = TRUE))

```

## Load the data

```{r tidy = FALSE, message = FALSE}

# Load the import data
import <- read.csv("output/build/monthly_cleaned.csv")
import = subset(import, select = -c(X))
import$year_month <- as.yearmon(paste(import$year, import$month), "%Y %B")
import = as_tibble(import)
import

```

```{r tidy = FALSE, message = FALSE}

# Subset to Vietnam
import_VN = import %>% 
  group_by(year_month, country_name) %>% 
  summarise(volume_sum = sum(volume_kg),
            value_sum = sum(value_USD)) %>% 
  filter(country_name %in% c("VIETNAM"))

import_VN

```

```{r tidy = FALSE, message = FALSE}

# Load the refusal data
load("output/build/compositeImportRefusal.Rdata")
refusal = as_tibble(composite) %>% 
  filter(catfish == 1) %>%
  arrange(date)
refusal

```

```{r tidy = FALSE, message = FALSE}

# Subset to Vietnam
refusal_VN = refusal %>% 
  mutate(year_month = as.yearmon(date, "%Y %B")) %>%
  group_by(year_month, country_std) %>%
  summarise(refusal_count = n()) %>%
  filter(country_std %in% c("VIETNAM"))

refusal_VN

```

## Merge import and refusal

```{r tidy = FALSE, message = FALSE}

dta_VN = import_VN %>%
  full_join(refusal_VN, by = "year_month") %>%
  select(-c(country_std)) %>%
  filter(year_month > as.yearmon("2013-12")) %>%
  filter(year_month < as.yearmon("2020-03")) %>%
#  mutate(USDA_dummy = ifelse(year_month > as.yearmon("2016-02"), 1, 0),
  mutate(USDA_dummy = ifelse(year_month > as.yearmon("2017-08"), 1, 0),
         year = year(year_month),
         month = month(year_month)) %>%
  replace_na(list(refusal_count = 0))
  
dta_VN

```

## Statistical Analysis

```{r tidy = FALSE, message = FALSE}

OLS1 <- lm(refusal_count ~ USDA_dummy + volume_sum, 
           data = dta_VN)

summ(OLS1, digits = 3)

```

```{r tidy = FALSE, message = FALSE}

# Create an interaction variable
dta_VN$USDAxVolume = dta_VN$USDA_dummy * dta_VN$volume_sum

OLS2 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume, 
           data = dta_VN)

summ(OLS2, digits = 3)

```

```{r tidy = FALSE, message = FALSE}

# Add factor(month)
OLS3 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume + factor(month), 
           data = dta_VN)

summ(OLS3, digits = 3)

```

```{r tidy = FALSE, message = FALSE}

export_summs(OLS1, OLS2, OLS3,
             model.names = c("Model 1","Model 2","Model 3"),
             digits = 3)

```

## Include all countries

```{r tidy = FALSE, message = FALSE}

import_all = import %>% 
  group_by(year_month, country_name) %>% 
  summarise(volume_sum = sum(volume_kg),
            value_sum = sum(value_USD))

import_all

```

```{r tidy = FALSE, message = FALSE}

refusal_all = refusal %>% 
  mutate(year_month = as.yearmon(date, "%Y %B")) %>%
  group_by(year_month, country_std) %>%
  summarise(refusal_count = n())

refusal_all

```

## Merge import and refusal

```{r tidy = FALSE, message = FALSE}

dta = import_all %>%
  full_join(refusal_all, by = c("year_month","country_name" = "country_std")) %>%
  filter(year_month > as.yearmon("2013-12")) %>%
  filter(year_month < as.yearmon("2020-03")) %>%
#  mutate(USDA_dummy = ifelse(year_month > as.yearmon("2016-02"), 1, 0),
  mutate(USDA_dummy = ifelse(year_month > as.yearmon("2017-08"), 1, 0),
         year = year(year_month),
         month = month(year_month)) %>%
  replace_na(list(refusal_count = 0))

dta
write.csv(dta,"output/build/ez_merged_data.csv")

```

## Statistical Analysis

```{r tidy = FALSE, message = FALSE}

OLS.1 <- lm(refusal_count ~ USDA_dummy + volume_sum, 
            data = dta)

summ(OLS.1, digits = 3)

```

```{r tidy = FALSE, message = FALSE}

# Create an interaction variable
dta$USDAxVolume = dta$USDA_dummy * dta$volume_sum

OLS.2 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume, 
            data = dta)

summ(OLS.2, digits = 3)

```

```{r tidy = FALSE, message = FALSE}

# Add factor(month)
OLS.3 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume + factor(month), 
            data = dta)

summ(OLS.3, digits = 3)

```

```{r tidy = FALSE, message = FALSE}

# Add factor(country_name)
OLS.4 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume + factor(month) + factor(country_name), 
            data = dta)

summ(OLS.4, digits = 3)

```

```{r tidy = FALSE, message = FALSE}

export_summs(OLS.1, OLS.2, OLS.3, OLS.4,
             model.names = c("Model 1","Model 2","Model 3","Model 4"),
             digits = 3)

```

## Heteroscedasticity-consistent Standard Errors

```{r tidy = FALSE, message = FALSE}

# coeftest(OLS.1, vcov = vcovHC(OLS.1, type = "HC1"))
# coeftest(OLS.2, vcov = vcovHC(OLS.2, type = "HC1"))
# coeftest(OLS.3, vcov = vcovHC(OLS.3, type = "HC1"))
coeftest(OLS.4, vcov = vcovHC(OLS.4, type = "HC1"))

```

## Vietnam, China, Thailand

```{r tidy = FALSE, message = FALSE}

# Subset to Vietnam, China, Thailand
import_VCT = import %>% 
  group_by(year_month, country_name) %>% 
  summarise(volume_sum = sum(volume_kg),
            value_sum = sum(value_USD)) %>% 
  filter(country_name %in% c("VIETNAM","CHINA","THAILAND"))

import_VCT

```

```{r tidy = FALSE, message = FALSE}

# Subset to Vietnam
refusal_VCT = refusal %>% 
  mutate(year_month = as.yearmon(date, "%Y %B")) %>%
  group_by(year_month, country_std) %>%
  summarise(refusal_count = n()) %>%
  filter(country_std %in% c("VIETNAM","CHINA","THAILAND"))

refusal_VCT

```

## Merge import and refusal

```{r tidy = FALSE, message = FALSE}

dta_VCT = import_VCT %>%
  full_join(refusal_VN, by = "year_month") %>%
  select(-c(country_std)) %>%
  filter(year_month > as.yearmon("2013-12")) %>%
  filter(year_month < as.yearmon("2020-03")) %>%
#  mutate(USDA_dummy = ifelse(year_month > as.yearmon("2016-02"), 1, 0),
  mutate(USDA_dummy = ifelse(year_month > as.yearmon("2017-08"), 1, 0),
         year = year(year_month),
         month = month(year_month)) %>%
  replace_na(list(refusal_count = 0))
  
dta_VCT

```

```{r tidy = FALSE, message = FALSE}

OLS11 <- lm(refusal_count ~ USDA_dummy + volume_sum, 
            data = dta_VCT)

# Create an interaction variable
dta_VCT$USDAxVolume = dta_VCT$USDA_dummy * dta_VCT$volume_sum

OLS22 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume, 
            data = dta_VCT)

# Add factor(month)
OLS33 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume + factor(month), 
            data = dta_VCT)

# Add factor(country_name)
OLS44 <- lm(refusal_count ~ USDA_dummy + volume_sum + USDAxVolume + factor(month) + factor(country_name), 
            data = dta_VCT)

```


```{r tidy = FALSE, message = FALSE}

export_summs(OLS11, OLS22, OLS33, OLS44,
             model.names = c("Model 1","Model 2","Model 3","Model 4"),
             digits = 3)

```
