---
title: "Merge Refusals with Import Volume"
author: "Vince Egalla"
date: "12/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 3)
options(scipen=999)
```

## Dependencies

```{r}
library(tidyverse)
library(plyr)
library(dplyr)
library(countrycode)
library(lubridate)
library(ggplot2)
library(knitr)
library(car)
library(AER)
library(tidyr)
library(ggplot2)
library(reshape2)
library(gridExtra)
library(lubridate)
library(RColorBrewer)
library(jtools)
library(stargazer)
library(huxtable)
```

## Load Data
```{r}
## Combined FDA + USDA data
load("output/build/compositeImportRefusal.Rdata")
```

```{r}
## Cleaned import volume data
import = read.csv("output/build/monthly_cleaned.csv")
```

## Convert refusal data to monthly
```{r}
## Create Year-Month variable for aggregation
composite$yrmonth = format(as.Date(composite$date),"%Y-%m")

## Aggregate refusal instances to a monthly level
monthlyRef = setNames(aggregate(composite$catfish, by=list(composite$yrmonth, composite$country_std), FUN= sum), c('yrmonth','country','total_refusals'))
```

## Convert volume data to monthly
```{r}
## Create Year-Month variable for aggregation
import$yrmonth = format(as.Date(paste(import$year,import$month_number,"01", sep="-")),"%Y-%m")

## Aggregate refusals to a monthly level
monthlyVol = setNames(aggregate(import$volume_kg, by=list(import$yrmonth, import$country_name), FUN= sum), c('yrmonth','country','import_volume'))
```

## Merge monthly data
```{r}
## Manual conversion of records with import refusal but no import volume for given month-country
# China - March 2016 -> February 2016
monthlyRef[monthlyRef$yrmonth == "2016-03" & monthlyRef$country == "CHINA",]

monthlyRef$yrmonth[(monthlyRef$yrmonth == "2016-03" & monthlyRef$country == "CHINA")] = format(as.Date("2016-02-01"),"%Y-%m")

monthlyRef[monthlyRef$yrmonth == "2016-02" & monthlyRef$country == "CHINA",]

# Thailand - January 2018 -> November 2017 (Latest 2017 record)
monthlyRef[monthlyRef$yrmonth == "2018-01" & monthlyRef$country == "THAILAND",]

monthlyRef$yrmonth[(monthlyRef$yrmonth == "2018-01" & monthlyRef$country == "THAILAND")] = format(as.Date("2017-11-01"),"%Y-%m")

monthlyRef[monthlyRef$yrmonth == "2017-11" & monthlyRef$country == "THAILAND",]

# Thailand - May 2018 -> February 2018 (No other records in 2018)
monthlyRef[monthlyRef$yrmonth == "2018-05" & monthlyRef$country == "THAILAND",]

monthlyRef$yrmonth[(monthlyRef$yrmonth == "2018-05" & monthlyRef$country == "THAILAND")] = format(as.Date("2018-02-01"),"%Y-%m")

monthlyRef[monthlyRef$yrmonth == "2018-02" & monthlyRef$country == "THAILAND",]

monthlyRef = setNames(aggregate(as.numeric(monthlyRef$total_refusals), by=list(monthlyRef$yrmonth, monthlyRef$country), FUN= sum), c('yrmonth','country','total_refusals'))
```

```{r}
# Limit to observations with import volume 
monthly = merge(x= monthlyRef, y= monthlyVol, by= c('yrmonth','country'), all.y= TRUE, fill= 0)

monthly[is.na(monthly)] = 0
```

## Add alternate scales of trade volume
```{r}
monthly$import_volume_100k = monthly$import_volume / 100000
monthly$import_volume_1M   = monthly$import_volume / 1000000
```

## Build Variables for regression analysis

```{r}
## Month & Year variables
typeof(monthly$yrmonth)
monthly$year = format(as.Date(paste(monthly$yrmonth,'-01',sep= '')), '%Y')
monthly$month = format(as.Date(paste(monthly$yrmonth,'-01',sep = '')), '%m')

typeof(monthly$year)

## Limit data to 2014 (FDA start) to 2020 February (USDA end)
monthly = monthly[monthly$year >= 2014,]
monthly = monthly[!(monthly$year == 2020 & !(monthly$month == '01' | monthly$month == '02')),]
```

## USDA Authority (Dummy)
```{r}
monthly = monthly %>%
  mutate(USDA_transition01 = ifelse((yrmonth >= as.yearmon("2016-03")) & (yrmonth < as.yearmon("2017-09")), 1, 0),
         USDA01 = ifelse(yrmonth > as.yearmon("2017-08"), 1, 0))


## Interaction of USDA Authority and Volume
monthly$USDAxVolume = monthly$USDA01 * monthly$import_volume
monthly$USDAxVolume100k = monthly$USDA01 * monthly$import_volume_100k
monthly$USDAxVolume1M = monthly$USDA01 * monthly$import_volume_1M

monthly$USDA_t01xVolume1M = monthly$USDA_transition01 * monthly$import_volume_1M

```

```{r}
monthly = monthly %>%
  mutate(country_cat = ifelse(((country == "VIETNAM") | (country == "CHINA") | (country == "THAILAND")), country, "ROW"))

monthly$country_cat <- factor(monthly$country_cat, levels = c("ROW","VIETNAM", "CHINA", "THAILAND"))

```

```{r}
## Export as CSV for comparison
write.csv(monthly, file="output/build/ve_analysis_dataset.CSV")


## Export as RData
save(monthly, file="output/build/ve_analysis_dataset.RData")
```

