---
title: "Import Rejection Consolidation"
author: "Vince Egalla"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dependencies

```{r}
library(tidyverse)
library(plyr)
library(dplyr)
library(countrycode)
library(lubridate)
library(ggplot2)
#library(extrafont)
#font_import()
#library(tabulizer)
```

## Load Data
```{r}
## Load linear regression results of models 1-3
load("output/analysis/ve_analysis_1_ols.Rdata")
load("output/analysis/ve_analysis_2_ols.Rdata")
load("output/analysis/ve_analysis_3_ols.Rdata")
```

```{r}
result = data.frame(c(coef(ols.1)[2],coef(ols.2)[2],coef(ols.3)[2]))

result = cbind(result,(c("Model 1", "Model 2", "Model 3")))

colnames(result)

names(result)[names(result) == "c.coef.ols.1..2...coef.ols.2..2...coef.ols.3..2.."] = "usda_coef"
names(result)[names(result) == "(c(\"Model 1\", \"Model 2\", \"Model 3\"))"] = "model"
```

```{r fig.width = 7, fig.height = 3, message = FALSE}

bluePalette <- c("#041E42","#6A98BA", "#CAE2E0")

## Plot of Coefficents
ggplot(result, aes(x= model, y= usda_coef, fill= model)) + 
  geom_bar(stat= "identity", legend= FALSE) + 
  labs(x= "", y= "", fill= "") + 
  theme_bw() +
  scale_x_discrete(labels = c("Total Refusals\nby USDA only", "Total Refusals\nby USDA and controls", "Food Safety Refusals\nby USDA and controls")) +
  ylim(-2,12) + 
  geom_hline(yintercept= 0, color= "black") +
  scale_fill_manual(values=bluePalette)

ggsave("output/figures/analysis/report_usdaCoefficients.png", dpi = 300)
```
